name: Build iOS (No Code Sign)

on:
  workflow_dispatch: 

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Lấy mã nguồn về máy ảo
        uses: actions/checkout@v3

      - name: Cài đặt Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Tải các thư viện (Dependencies)
        working-directory: ./app_mobile_lich-main
        run: flutter pub get

      - name: Dọn dẹp CocoaPods & Ép hệ thống nhận iOS 15.0
        working-directory: ./app_mobile_lich-main/ios
        run: |
          echo "1. Dọn dẹp cache Pods..."
          rm -f Podfile.lock
          rm -rf Pods
          rm -rf .symlinks
          
          echo "2. Ép Xcode project lên 15.0..."
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' Runner.xcodeproj/project.pbxproj
          
          echo "3. Ép AppFrameworkInfo.plist lên 15.0..."
          if [ -f "Flutter/AppFrameworkInfo.plist" ]; then
            sed -i '' 's/<string>[0-9.]*<\/string>/<string>15.0<\/string>/g' Flutter/AppFrameworkInfo.plist
          fi

      - name: Biên dịch ra file .app iOS
        working-directory: ./app_mobile_lich-main
        run: flutter build ios --release --no-codesign

      - name: Đóng gói thành file .ipa chuẩn
        working-directory: ./app_mobile_lich-main/build/ios/iphoneos
        run: |
          mkdir Payload
          cp -R Runner.app Payload
          zip -r Payload.zip Payload
          mv Payload.zip Quản_Lý_Lịch.ipa

      - name: Xuất file cài đặt ra ngoài
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App-IPA
          path: app_mobile_lich-main/build/ios/iphoneos/Quản_Lý_Lịch.ipa